### ISSUE TITLE
Ansible update for Tumbleweed qt5 libraries needed

### ISSUE THREAD

**Issue by garybuhrmaster** [MythTV/ansible#20]
OpenSUSE tumbleweed no longer makes available the qt5 webkit libraries, and those libraries need to be removed from the (default) qt5 list.

**Comment by billmeek** [comment]
On 9/18/22 21:23, Gary Buhrmaster wrote:
> OpenSUSE tumbleweed no longer makes available the qt5 webkit libraries, and those libraries need to be removed from the (default) qt5 list.

These were removed in the merge done 'Tue Sep 20 10:58:13 2022 -0500'

Please verify, thanks.

-- 
Bill

**Comment by garybuhrmaster** [comment]
> On 9/18/22 21:23, Gary Buhrmaster wrote: OpenSUSE tumbleweed no longer makes available the qt5 webkit libraries, and those libraries need to be removed from the (default) qt5 list.
> These were removed in the merge done 'Tue Sep 20 10:58:13 2022 -0500' Please verify, thanks.
> […](#)
> -- Bill

A quick look suggests that your merge accomplishes the necessary changes.  Closing this issue.
