### ISSUE TITLE
mythtv-macports fails in "Get mysqlclient libs"

### ISSUE THREAD

**Issue by ulmus-scott** [MythTV/ansible#54]
The GitHub Actions builds of MythTV on macOS all fail with the following: (from https://github.com/MythTV/mythtv/actions/runs/9327468342/job/25677394252)

```
TASK [mythtv-macports : Get mysqlclient libs] **********************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/local/lib/mysql8/pkgconfig/ && /opt/local/bin/pkg-config --libs mysqlclient", "delta": "0:00:00.012425", "end": "2024-06-01 05:02:35.360307", "msg": "non-zero return code", "rc": 1, "start": "2024-06-01 05:02:35.347882", "stderr": "Package mysqlclient was not found in the pkg-config search path.\nPerhaps you should add the directory containing `mysqlclient.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'mysqlclient' found", "stderr_lines": ["Package mysqlclient was not found in the pkg-config search path.", "Perhaps you should add the directory containing `mysqlclient.pc'", "to the PKG_CONFIG_PATH environment variable", "No package 'mysqlclient' found"], "stdout": "", "stdout_lines": []}
```

The PKG_CONFIG_PATH (`.../mysql8/pkgconfig/`) is different from what I saw [here](https://stackoverflow.com/questions/76876823/cannot-install-mysqlclient-on-macos#comment138467322_78154242)  (`.../mysql8/lib/pkgconfig`) and in the [py-mysqlclient](https://ports.macports.org/port/py-mysqlclient/details/) macport [here](https://github.com/macports/macports-ports/blob/e7bc28279d9f5d7b0fa8e5abbcdd1d432e63c9a5/python/py-mysqlclient/Portfile#L58) (`.../mysql8/mysql/pkgconfig`).  It is not clear to me that [manually setting](https://github.com/PyMySQL/mysqlclient?tab=readme-ov-file#customize-build-posix) MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS is necessary.

@jhoyt4 Ideas?  Would using the py-mysqlclient macport work?

**Comment by jhoyt4** [comment]
The issue is due to an upstream issue with MySQL8 on the macports side.   When they upgraded to 8.4 the MySQL/lib directory structure got messed up.

A ticket and PR have both been created on macports site.

Nothing much to be done until the macports dev get the fix applied.

https://trac.macports.org/ticket/70001

**Comment by jhoyt4** [comment]
I ended up rolling up my sleeves and attempted to fix the issue upstream [with macports](https://github.com/macports/macports-ports/pull/24615)

I'm testing the fix on unofficial macOS currently (hoping there's no other issues).

I'll add a note if/when that resolves.

**Comment by jhoyt4** [comment]
Well, now I need to wait for the updated mysql8-8.4.0_3 to propagate into macport's default ports database (that should happen sometime overnight).

Everything installs / builds fine locally, but I my local macports port database is updated directly from macports git repo. Implementing that same mechanism is WAY too slow on first git pull for the mythtv CI chain (hours vs minutes to update the ports list).

I'll check back later and report progress.

**Comment by jhoyt4** [comment]
This should now be resolved.  I'll keep an eye on the mythtv repo's actions in case something I missed emerges.

**Comment by ulmus-scott** [comment]
I rebased one of my pull requests and the macOS GitHub Actions runners succeeded. https://github.com/MythTV/mythtv/actions/runs/9627023985?pr=910
